### ISSUE TITLE
can't start, OSX Anaconda installed already

### ISSUE THREAD

**Issue by hexindent** [yhat/rodeo#144]
Anaconda-2.3.0-MacOSX-x86_64.pkg, OSX Yosemite.

Anaconda installed at `~/anaconda`, can't install for all users on this computer

**Comment by glamp** [comment]
To clarify, is the issue you can't start Rodeo, or that it's not installed for all users?

**Comment by mgrady3** [comment]
I had a similar issue  where I couldn't start rodeo even though Anaconda was already installed.

my problem was fixed by making sure my $PATH variable had ~/anaconda/bin: before everything else. So I went ahead an added the following line to my .bash_profile:

export PATH="/Users/MyUserName/anaconda/bin:$PATH"

**Comment by hexindent** [comment]
I meant... I can't install Anaconda for all users. Rodeo is fine in terms of installation. When it starts, the pop-up says "Oops! Rodeo can't start..." and something like installing Anaconda will fix it, while it doesn't...

I kinda fixed it (ignore it) by uninstall Anaconda then installing it again. The issue occurred after I updated the packages with pip, which updated a lot of packages that have newer versions than those packed in Anaconda 2.3.0. If I install 2.3.0 and choose not to update any package, the issue doesn't happen. I might have to update the packages when there's a new release of Anaconda.

**Comment by iron0012** [comment]
Thanks very much mgrady3, your solution solved my problems with this same issue!

**Comment by mgrady3** [comment]
No problem, glad I could help. I believe the Rodeo error message that pops up hints that this is a likely solution but they do not explain clearly how to fix the issue as there is not a simple way to explain the solution in a very concise manner.

Rodeo requires or suggests anaconda to be needed as that's the easiest way to get access to the IPython kernel. However, when installing multiple versions of python on the same OS (OS X default python, Anaconda, macports python, homebrew python, etc...), for beginner users, if you are not careful with your installations, it is easy to mess up your $PATH variable so that Rodeo will be unhappy when it invokes the 'python' command even though you may already have installed Anaconda.

This is a problem I have run into a number of times over the years because I'm still relatively a novice when it comes to managing projects using multiple versions of python. Luckily I found this fix to be my general go to when I have problems with my Anaconda installation.

**Comment by glamp** [comment]
Please try out the new "Python PATH Triage" feature in 1.2.0!
8314d79604c17faf40e506467c6b5a3b5a2308f3
