### ISSUE TITLE
not recognizing PYTHONPATH or other Environment Variables

### ISSUE THREAD

**Issue by chriscate** [yhat/rodeo#231]
I'm using Rodeo in combination with pyspark.  To use pyspark via python/ipython, a few environment variables must be set.  I have these in my .bashrc and everything works fine when doing something like `from pyspark import SparkContext` in terminal, but Rodeo does not pick these variables up and produces an error (no module named pyspark) when running the same code.

I got it to work in Rodeo, but I had to add the lines below to my .rodeoprofile.  It seems like Rodeo's python/ipython environment should match that of the terminal and that this step should not be necessary...

```
import os
import sys

os.environ['SPARK_HOME'] = '/usr/local/spark-1.6.0-bin-hadoop2.6'
sys.path.append('/usr/local/spark-1.6.0-bin-hadoop2.6/python')
sys.path.append('/usr/local/spark-1.6.0-bin-hadoop2.6/python/lib/py4j-0.9-src.zip')
```

**Comment by glamp** [comment]
So desktop apps do some very annoying things when it comes to environment variables. At least on Mac, they don't actually run as "you". They're running as a more restricted version of yourself (I think  that's from an Alanis Morissette song). Essentially what happens is your `.bashrc` / `.bash_profile` don't get automatically loaded and you're left with sort of the minimum amount of "PATH stuff" for your Rodeo app.

The way Rodeo tries to work around this is by letting [Steve Irwin handle things](https://github.com/yhat/rodeo/blob/master/src/rodeo/steve-irwin.js#L16). Unfortunately it doesn't always work (as in your case). I'm guessing that it's possbile that for some reason the [`getUserPath`](https://github.com/yhat/rodeo/blob/master/src/rodeo/steve-irwin.js#L9) function isn't running.

@cgc17 Could you take a look at the logs (View > Toggle Dev Tools) and let me know what you see? This would be make things a lot easier for me to debug :smile: 

![](http://images4.fanpop.com/image/photos/14900000/-Ironic-alanis-morissette-14973697-720-480.jpg)

**Comment by cgc17** [comment]
@glamp no problem... here is what I am seeing in the logs:

/Applications/Rodeo.app/Contents/Resources/atom.asar/common/api/lib/deprecate.js:89 (electron) ipc module is deprecated. Use ipcRenderer module instead.
desktop-main.js:1 [LOG]: UPDATE AVAILABLE
desktop-main.js:1 [LOG]: {"sender":{"_events":{},"_eventsCount":4}}
desktop-main.js:1 [LOG]: [ERROR]: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.: (null)
desktop-main.js:1 [LOG]: using python: /usr/local/bin/python

**Comment by gwerbin** [comment]
In my case, the issue is a little deeper than just looking for and sourcing a Bash script.

That aside, I'm on OSX 11, and I have a launch agent configured to set my `PATH` and `PYTHONPATH` using launchctl. I don't know how GUI applications find environment variables, and this seems to work for some applications (R, MacVim) but not others, notably Rodeo. Ironically, the main reason I even bothered with launchctl was to try to get Rodeo to find R (so I could use http://rpy2.readthedocs.org/en/version_2.7.x/) without having to set it in my `.rodeoprofile` file. Is this a bug? I checked `process.env` in the console and none of the variables I set with launchctl are there.

Alternatively, would be too dirty of a hack to try and actually get environment variables by launching a shell?
