### ISSUE TITLE
electron not functioning

### ISSUE THREAD

**Issue by missing-semicolon** [yhat/rodeo#247]
I thought I'd take a stab at solving the issue I opened today  (#246)  but after forking and cloning the repo, I am unable to start dev mode

After typing: 
> electron .

I receiving the following error:

> The app provided is not a valid Electron app, please read the docs on how to write one:
> https://github.com/atom/electron/tree/v0.36.9/docs
> 
> Error: Cannot find module 'fs-extra'

Is this a known issue?

**Comment by kmatt** [comment]
Having same problem (OS X 10.11), using Node components installed via Homebrew. Tried manually installing dependencies, but the chain seemed to be never ending.

Depencency list on https://github.com/yhat/rodeo/blob/master/DEV.md does not seem to be complete?

**Comment by brucechou1983** [comment]
Do you run `npm install` before `electron .`?

**Comment by TakenPilot** [comment]
I've run into this issue as well for the latest version of Rodeo, and my solution was to install it temporarily until the new version (with the fix) is released.  That is:

```
npm install --save fs-extra
```

**Comment by baito** [comment]
Same bug here. (L)Ubuntu 14.04.

**Comment by TakenPilot** [comment]
The latest version on master installed without that dependency.  I can `rm -rf node_modules && npm install` now, whereas before I also got that message.

I'm going to marked this bug as fixed, since this was one of the first things I did when I was hired a few weeks ago.

The latest on master (1.4.x) looks quite a bit different than before (1.3.x).  I removed some features to fix the stability issues, and I'm slowly adding the old code back on top of the rebuilt foundation.  It does less now, but _it definitely won't crash_.  Gimme a few more weeks and this thing will be brilliant.
