### ISSUE TITLE
current working directory not correct

### ISSUE THREAD

**Issue by redoxmatlab** [yhat/rodeo#304]
I discovered serious issues with the setting 'current working directory' as in some cases if you select a directory Rodeo will not set it to working correctly. More annoying that when this happens the console does not tell you much about it ...probably I was assuming it works fine and I was looking for other issues.

**Comment by redoxmatlab** [comment]
Just to add that in order to get working directory correct, I have to select directory and then restart Rodeo at that point the WD is set correctly!

**Comment by TakenPilot** [comment]
The current thinking is that the file viewer and the console can have different working directories.  The reason is that eventually there will be _multiple_ consoles and file viewers, perhaps all in different directories.

This isn't really a bug, and I'm going to try and make the difference more clear.
