### ISSUE TITLE
High cpu usage for Rodeo 2.0 on OS X

### ISSUE THREAD

**Issue by markof1** [yhat/rodeo#345]
I installed Rodeo 2.0 yesterday and noticed that whenever I import packages (i.e sys, time, csv, os) in a Rodeo session the cpu usage for the python2.7 process goes to 99.9% of cpu.

**Comment by aechase** [comment]
I also have this issue on OS X 10.11.5. I typed `import sys` into the Rodeo console, and the python3.4 process jumped to around 100% CPU; didn't come down until I quit the app.

**Comment by TakenPilot** [comment]
It's because of how the code is polling for new content from IPython, which was taken from Rodeo 1.x.  It's still doing a while true; yield.

Battery life isn't so badly affected because it yields to the next process immediately, but polling is never ideal.  I've thought of two better ways to do this, so I'm going to be exploring those soon.
