### ISSUE TITLE
No help tab in Rodeo 2.0.4 on OSX 10.10.4

### ISSUE THREAD

**Issue by ttimbers** [yhat/rodeo#364]
I am running Rodeo 2.0.4 on OSX 10.10.4 and I cannot see a help tab, and thus I cannot get any help documentation for anything. This is what my Rodeo IDE looks like:

![screen shot 2016-07-06 at 9 03 15 am](https://cloud.githubusercontent.com/assets/6865016/16625316/bd5617b0-4358-11e6-8da2-7f8153d1c9e3.png)

**Comment by ben519** [comment]
I think you can do `help(round)` but unfortunately the documentation pops up in the Console instead of a separate window.  I requested to get this improved on the [feature rodemap](http://discuss.yhat.com/t/rodeo-feature-roadmap/48/7).

**Comment by ttimbers** [comment]
@ben519 thanks for this - that gives me something to work with for now!

**Comment by TakenPilot** [comment]
I'm trying to get a release out later today that will include the fix for this:  https://github.com/yhat/rodeo/pull/366

It'll look like this:

<img width="1078" alt="screen shot 2016-07-06 at 5 34 45 pm" src="https://cloud.githubusercontent.com/assets/4154804/16656831/260c89f8-442e-11e6-8232-5fee1ec64eb4.png">

**Comment by TakenPilot** [comment]
It's in 2.0.5, available since last night.  : )
