### ISSUE TITLE
confused by versions(series) of rodeo

### ISSUE THREAD

**Issue by xiekunwhy** [yhat/rodeo#391]
What's the differences between Rodeo 0.44 Rodeo 2.xx and Rodeo 1.3x.

**Comment by TakenPilot** [comment]
Mostly the date that it was built.

1.3.x was the version from earlier this year.  Then I was hired a few months ago to redo the foundation of Rodeo so it would stop freezing and crashing, and that became 1.4.x, then for marketing reasons ("Hey, it doesn't crash anymore and also doesn't eat memory and also is really fast!"), it became 2.0.x

2.1.x will be the official Windows release, probably.

Other things that are almost done and that will be new minor versions:
- multi-windows so that data scientists can take advantage of the usual multi-monitor setup
- better panda's DataFrame features (in particular, more data science focused than PyCharm)
- pdf and markdown and notebook integration
- git integration, and excel integration, and database integration, and projects...
- tons more stuff

Now that we have a stable platform, I'm really excited about all the cool stuff we can build.

**Comment by xiekunwhy** [comment]
TakenPilot,
Thank you for your answer. Any information about Rodeo 0.4.4(the default version be installed using pip)?

**Comment by TakenPilot** [comment]
From what I was told, it hasn't been updated in a very long time, and was a kind of experiment.  On Monday I'll ask if it can be removed, since it's probably confusing to have it there.

**Comment by xiekunwhy** [comment]
Ok, thanks! Hope rodeo getting better and better.
