### ISSUE TITLE
Freeze upon command

### ISSUE THREAD

**Issue by dpessoaIGC** [yhat/rodeo#427]
Just installed Rodeo 2.1.1 on a Mac OS X 10.11.6. I can write in the console but as soon as I press enter it freezes indefinitely, even kernel restart fails.

I installed rodeo through easy_install and have checked that jupyter is installed (version 1.0.0).

Here is the log file
[rodeo.log.txt](https://github.com/yhat/rodeo/files/423259/rodeo.log.txt)

**Comment by ben519** [comment]
Did you set the correct Python path? (Settings > Python > Python Command)

**Comment by dpessoaIGC** [comment]
Yes, it is /usr/bin/python, the same as the output of "which python" in the terminal

**Comment by TakenPilot** [comment]
@glamp Can we remove Rodeo from pip please?  It's really confusing everyone.  🎱 

@dpessoaIGC That version is _really_ out of date.  ⌛ 

@ben519 This is the right answer.  💯   Also, it can be just a command like `python` instead of the full path.  This is really useful with aliases in bash.

I've been working this past week to change the preferences and startup screens to make the _command_ aspect more obvious, because there are a lot of people trying to type in the full paths and making typos.  I've also added a file-picker to prevent these typos, and a bunch of useful working directory stuff as well.  It's going to be awesome.  These will be out in the next release for sure.

**Comment by dpessoaIGC** [comment]
@TakenPilot I know it's not the same, just thought it might install dependencies, such as jupyter. Or is it the jupyter version that it really out of date?

**Comment by ben519** [comment]
@TakenPilot [Sounds awesome](http://imgur.com/gallery/hVJ719e)

**Comment by glamp** [comment]
@TakenPilot it is done 🔪

**Comment by TakenPilot** [comment]
Thanks!  I'm going to close this and keep on working.  ⏩

**Comment by dpessoaIGC** [comment]
I'm sorry I wasn't clear, I installed Rodeo with the DMG. I then installed also the very outdated one through pip. 

I just installed jupyter through pip install but the up-to-date Rodeo is still freezing. Issue not solved..
