### ISSUE TITLE
Command that I use to run python: No such file or command

### ISSUE THREAD

**Issue by essicolo** [yhat/rodeo#456]
**Rodeo 2.2.0**. To avoid conflicts between the core python and Anaconda on Linux, I use to create an alias in ~.bashrc:

```
alias activate_anaconda="source ~/bin/anaconda3/bin/activate root"
```

When Rodeo asks me "What is the command that you use to run python?", I reply:

```
activate_anaconda && python
```

The command runs fine in the terminal. But Rodeo tells me "There was an error running python":

```
No such file or command
```

![no-such-file-or-command](https://cloud.githubusercontent.com/assets/5118227/18488712/a5fc798c-79c8-11e6-8d65-f208363057ae.png)

**Comment by glamp** [comment]
The python command in Rodeo doesn't support multiple cmd runs (or whatever you want to call  `&&` :) ).

One thing you could do to fix the issue is to put `activate_anaconda` in your bashrc. The downside would be that the anaconda environment would be your default python (which I totally realize might be why you have this in the first place).

Another thing to try would be to put the full path to your "anaconda python" in the Rodeo python command field. For example, mine would be `/Users/glamp/miniconda2/bin/python` (while my system one would be `/usr/bin/python`). Based on your screenshots, it would most likely be something like  `~/bin/anaconda3/bin/python`

Give it a try and let me know if it works!

**Comment by essicolo** [comment]
Wonderful. ` ~/bin/anaconda3/bin/python` works perfectly!
