### ISSUE TITLE
Rodeo doesn't find new version

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#497]
When I start Rodeo and click on Help > Check For Updates, it says I have the latest updates, but I'm using 2.4.2 and I see that 2.4.3 is available.

<img width="1680" alt="screen shot 2016-10-08 at 7 39 46 am" src="https://cloud.githubusercontent.com/assets/723099/19212899/cd76f5a8-8d2a-11e6-9525-cabc28a38441.png">

Also, isn't Rodeo supposed to automatically update itself?  Or am I mistaken?

FYI, this isn't a big deal for me - I usually just download the new version and install it manually.  Just thought I'd report the bug(?).

**Comment by TakenPilot** [comment]
Right!  This is true.  The only change in version [2.4.3](https://github.com/yhat/rodeo/releases/tag/v2.4.3) is the introduction of a cat gif for the Windows installer.

![installing](https://raw.githubusercontent.com/yhat/rodeo/master/build/install-spinner.gif)

The reason is that the default installing gif of green code was really confusing some people about what was happening, so we had to replace it with something more explicit.

**Comment by ben519** [comment]
Got it. And you know your job is cool when your solution to a problem is a cat gif.
