### ISSUE TITLE
A better alternative to Python IDE

### ISSUE THREAD

**Issue by leavor** [yhat/rodeo#678]
It seems that it is no longer updated and maintained. 
A better alternative is the spyder IDE.
[https://github.com/spyder-ide/spyder](url)

**Comment by david-bonin** [comment]
2c. Just a thought here. I keep seeing comments like these, which are basically Spyder marketing.

Yes Rodeo is not developed anymore but the code remains open source and frankly if people are still interested in it it's because some of its features and design were better than Spyder. 

Most people using Python are aware of Spyder, so instead of pushing Spyder on these pages let's talk about Rodeo instead.

**Comment by CAM-Gerlach** [comment]
Unlike myself (although I'm no longer a Spyder developer), this user has no affiliation whatsoever with Spyder, at least that I'm aware of, so I'm not sure how its advertising per say. However, I agree this issue is rather spammy. Its fair to bring up Spyder as an alternative but just spamming a new issue like this is rather silly.

If its realistic to fork Rodeo and get together a community team to maintain it, then that's excellent. At least as of a couple years ago, Rodeo was my second choice as a Python data science IDE after Spyder, and its good to have options (especially those that are community-developed rather than corporate, like most other big Python IDEs). However, if there isn't a realistic prospect of the project coming back, it might be better to try to port those missing features over to Spyder if possible.
